#' read rasters generated by RAP
#' 
#' 
#' RAP raw data bands contain % cover for the following categories:
#'   band 1 = annual forb and grass
#'   band 2 = bare ground
#'   band 3 = litter
#'   band 4 = perennial forb and grass
#'   band 5 = shrub
#'   band 6 = tree
#'   band 7-12 = uncertainty for bands 1-6
#' no data value = 65535
#' see "data_README.txt" for more info
#' 
#' I combined shrub and tree cover since the two function the same in this system
#' 
#' this script converts these covers to non-overlapping state categories:
#'   state 1 = grass: shrub < 1% and perennial forb/grass >=3%
#'   state 2 = mixed: shrub >=1%, shrub <15%, and perennial forb/grass >=3%
#'   state 3 = shrub: shrub >=15% and any grass cover
#'   state 4 = barren: shrub <15% and perennial forb/grass <3%
#' 
#' EMC 9/13/21
#' last update: 11/4/21

library(dplyr)
library(ggplot2)
library(raster)

file_list = list.files('RAP/raw files', pattern = '*.tif', full.names=T)

#raw_file <- 'RAP/raw files/RAP_cover_v2_1988.tif'

for (raw_file in file_list) {
  # get year from file name
  year = unlist(strsplit(tools::file_path_sans_ext(basename(raw_file)),'_'))[4]
  
  # read in raster stack
  s = stack(raw_file)
  
  # create objects for important raster layers
  perennialforbgrass = s@layers[[4]]
  shrubcover = s@layers[[5]]
  treecover = s@layers[[6]]
  
  perennialuncert = s@layers[[10]]
  
  # convert missing values to NA
  perennialforbgrass[perennialforbgrass==65535] <- NA
  shrubcover[shrubcover==65535] <- NA
  treecover[treecover==65535] <- NA
  
  perennialuncert[perennialuncert==65535] <- NA
  
  # combine shrub and tree
  shrubtree = shrubcover + treecover
  
  # create empty raster the same size
  stateraster = shrubcover
  values(stateraster) <- 0
  
  # inequalities to assign states (won't be able to tell invaded)
  # 1 = grass; 2 = mixed; 3 = shrub; 4 = barren; 5 = invaded
  stateraster[shrubtree<1 & perennialforbgrass>=3] <- 1
  stateraster[shrubtree>=1 & shrubtree <15 & perennialforbgrass>=3] <- 2
  #stateraster[shrubtree>=1 & perennialforbgrass>=5] <- 2
  stateraster[shrubtree>=15 ] <- 3
  stateraster[shrubtree<15 & perennialforbgrass<3] <- 4
  
  plot(stateraster, main=year)

  writeRaster(stateraster, filename=paste0('RAP/state_raster_', year, '.tif'), overwrite=T)
}
