#' read rasters generated by RAP
#' 
#' 
#' RAP raw data bands contain % cover for the following categories:
#'   band 1 = annual forb and grass
#'   band 2 = bare ground
#'   band 3 = litter
#'   band 4 = perennial forb and grass
#'   band 5 = shrub
#'   band 6 = tree
#'   band 7-12 = uncertainty for bands 1-6
#' no data value = 65535
#' see "data_README.txt" for more info
#' 
#' 
#' this script converts these covers to non-overlapping state categories:
#'   state 1 = grass: shrub < 1% and perennial forb/grass >=3%
#'   state 2 = mixed: shrub >=1%, shrub <15%, and perennial forb/grass >=3%
#'   state 3 = shrub: shrub >=15% and any grass cover
#'   state 4 = barren: shrub <15% and perennial forb/grass <3%
#' 
#' EMC 9/13/21

library(dplyr)
library(ggplot2)
library(raster)

raw_rap <- 'C:/Users/echriste/test1.tif'
s = stack(raw_rap)


# create objects for each raster layer
annualcover = s@layers[[1]]
barecover = s@layers[[2]]
perennialforbgrass = s@layers[[4]]
shrubcover = s@layers[[5]]
treecover = s@layers[[6]]


# create empty raster the same size
stateraster = annualcover
values(stateraster) <- 0

# inequalities to assign states (won't be able to tell invaded)
# 1 = grass; 2 = mixed; 3 = shrub; 4 = barren; 5 = invaded
stateraster[shrubcover<1 & perennialforbgrass>=3] <- 1
stateraster[shrubcover>=1 & shrubcover<15 & perennialforbgrass>=3] <- 2
stateraster[shrubcover>=15] <- 3
stateraster[shrubcover<15 & perennialforbgrass<3] <- 4

plot(stateraster)

